c_stdlib_version:     # [osx]
  - '11.0'            # [osx and arm64]
  - '10.13'           # [osx and x86_64]
occt:
  - 7.8.1  # [not linux]
  - 7.7.2  # [linux]
qt_main:  # [linux]
  - '5.15.13'  # [linux]
vtk:  # [linux]
  - 9.2.6  # [linux]
libboost_devel:  # [linux]
  - '1.82'  # [linux]
pcl:  # [linux]
  - 1.14.0  # [linux]