channel_sources:
- conda-forge/label/pivy_rc, conda-forge, defaults
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '11.0'                 # [osx and arm64]
  - '10.13'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx]
  - '11.0'                 # [osx]
qt6_main:
  - '6.6'
