channel_sources:
  - freecad/label/qt6, conda-forge/label/pivy_rc,conda-forge
channel_targets:
  - freecad qt6
MACOSX_SDK_VERSION:
  - '11.0'
c_stdlib_version:          # [osx]
- '11.0'                   # [osx and arm64]
- '10.13'                  # [osx and x86_64]
