{% set name = "freecad" %}
{% set version = "0.18b0" %}
{% set sha256 = "5737252019f778d49f7ef0befd17f90462bee67d513364320a5bc900773fc9e2" %}
{% set commit = "2a6655e1768d80e0098d410989ae02c622f2e698" %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/FreeCAD/FreeCAD/archive/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - osx.patch  # [osx]
        - osx1.patch  # [osx]
        - smesh.patch  # [osx]
        - win_unicode.patch

build:
    number: 4

requirements:
    build:
        - {{ compiler("cxx") }}
        - cmake
        - ninja
        - git
    host:
        - boost-cpp
        - python
        - qt
        - qtwebkit  # [osx]
        - occt
        - xerces-c
        - zlib
        - vtk 8.1.1
        - swig
        - eigen
        - pybind11
        - matplotlib
        - coin3d
        - pivy
        - pyside2
        - smesh
        - netgen  # [not win32]
        - doxygen
        - hdf5 1.10.1
        - libglu  # [linux]
        - mesalib  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxt  # [linux]
    run:
        - {{ pin_compatible("pyside2") }}
        - occt
        - vtk
        - qt
        - qtwebkit  # [osx]
        - xerces-c
        - zlib
        - boost-cpp
        - hdf5
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - smesh
        - netgen  # [not win32]
        - libglu  # [linux]
        - mesalib  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxt  # [linux]

test:
    commands:
        - FreeCADCmd -t 0

about:
    home: https://www.freecadweb.org/
    license: LGPL2
    license_family: LGPL
    license_file: COPYING
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://www.freecadweb.org/wiki/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - looooo
