{% set name = "freecad" %}
{% set version = "0.19.3" %}
{% set build_number = 0 %}
{% set build_number = build_number + 1000 %}  # [FEATURE_DEBUG]
{% set build_number = build_number + 2000 %}   # [vtk_build_variant == "osmesa"]
{% set build_number = build_number + 3000 %}   # [vtk_build_variant == "qt"]

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/{{ version }}/freecad_source.tar.gz
    sha256: 5a99fb95e7082f6eb5138f577f4348f5b348f038566b3765ae8f9f7241af9d6e

build:
    number: {{ build_number }}
    skip: true  # [py < 38]

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux and build_variant != "osmesa"]
        - {{ cdt('mesa-dri-drivers') }}      # [linux and build_variant != "osmesa"]
        - {{ cdt('mesa-libegl-devel') }}     # [linux and build_variant != "osmesa"]
        - {{ cdt('libselinux') }}            # [linux and build_variant != "osmesa"]
        - {{ cdt('libxdamage') }}            # [linux and build_variant != "osmesa"]
        - {{ cdt('libxfixes') }}             # [linux and build_variant != "osmesa"]
        - {{ cdt('libxxf86vm') }}            # [linux and build_variant != "osmesa"]
        - {{ cdt('libxcb') }}                # [linux and build_variant != "osmesa"]
        - {{ cdt('libxext') }}               # [linux and build_variant != "osmesa"]
        - {{ cdt('xorg-x11-server-xvfb') }}  # [linux and build_variant != "osmesa"]
        - {{ cdt('libxau') }}                # [linux and build_variant != "osmesa"]
        - {{ cdt('libxi-devel') }}           # [linux]
        - cmake
        - ninja
        - sed  # [unix]
    host:
        - boost-cpp
        - python
        - qt
        - occt
        - xerces-c
        - zlib
        - vtk * qt*  # [vtk_build_variant == "qt"]
        - vtk * osmesa*  # [vtk_build_variant == "osmesa"]
        - vtk * egl*  # [vtk_build_variant == "egl"]
        - swig
        - eigen
        - pybind11 =2.7
        - coin3d
        - pivy
        - pyside2
        - smesh >=9.7
        - doxygen
        - hdf5
        - xorg-libxt  # [linux]
        - freetype
        - libspnav  # [linux]
        - pcl
        - six
        - ply
        - tbb-devel
    run:
        - pyside2
        - vtk * qt*  # [vtk_build_variant == "qt"]
        - vtk * osmesa*  # [vtk_build_variant == "osmesa"]
        - vtk * egl*  # [vtk_build_variant == "egl"]
        - occt
        - qt
        - xerces-c
        - zlib
        - boost-cpp
        - hdf5
        - python
        - coin3d
        - pivy
        - {{ pin_compatible('smesh', max_pin='x.x.x') }}
        - xorg-libxt  # [linux]
        - freetype
        - numpy
        - six
        - pyyaml
        - libspnav  # [linux]
        - pcl
        - ply
    run_constrained:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
    commands:
        - freecadcmd -t 0  # [unix]

about:
    home: https://www.freecadweb.org/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://www.freecadweb.org/wiki/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - looooo
