{% set name = "freecad" %}
{% set version = "0.21.pre" %}
{% set build_number = 111 %}
{% set build_number = build_number + 500 %}  # [FEATURE_DEBUG]

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/freecad_source.tar.gz
    fn: freecad_source_{{ build_number }}.tar.gz
    # sha256:
    patches:
        - patches/temporary_win.patch  # [win]
        - patches/disable_git_info.patch
        - patches/qtwebengine_disable_sandbox.patch  # [linux]
        - patches/do_not_build_tests.patch  # [win]
        - patches/findcoin3d.patch  # [win]
        - patches/osx_arm64_cross_compiling.patch  # [osx and arm64]

build:
    number: {{ build_number }}
    skip: true  # [py < 311]

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('libselinux') }}            # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - cmake
        - ninja
        - sed  # [unix]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    host:
        - boost-cpp
        - python
        - qt-main
        - qt-webengine
        - occt
        - xerces-c
        - zlib
        - vtk
        - swig
        - eigen
        - pybind11
        - coin3d
        - pyside2
        - smesh ==9.9
        - doxygen  # [build_platform == target_platform]
        - hdf5
        - freetype
        - libspnav  # [linux]
        - pcl
        - six
        - ply
        - matplotlib
    run:
        - pyside2
        - vtk
        - occt
        - qt-main
        - qt-webengine
        - xerces-c
        - zlib
        - boost-cpp
        - hdf5
        - python
        - coin3d
        - pivy
        - {{ pin_compatible('smesh', max_pin='x.x.x') }}
        - freetype
        - numpy
        - six
        - pyyaml
        - libspnav  # [linux]
        - pcl
        - ply
        - gmsh
        - graphviz
    run_constrained:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

# test:
#    commands:
#        - freecadcmd -t 0  # [not win]

about:
    home: https://www.freecadweb.org/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://www.freecadweb.org/wiki/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - looooo
