{% set name = "freecad" %}
{% set version = "1.0.0" %}
{% set build_number = 0 %}
{% set build_number = build_number + 500 %}  # [FEATURE_DEBUG]

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/FreeCAD/FreeCAD/releases/download/{{ version }}/freecad_source.tar.gz
    sha256: b5af251615eeab3905b2aa5fbd432cf90c57b86f9ba2a50ca23c9cc1703f81d9
    patches:
        - patches/osx_arm64_cross_compiling.patch    # [osx and arm64]

build:
    number: {{ build_number }}
    skip: true  # [py > 311]

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('libselinux') }}            # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - cmake
        - swig
        - ninja
        - sed                                    # [unix]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    host:
        - libboost-devel
        - python
        - qt-main
        - occt
        - xerces-c
        - zlib
        - vtk
        - eigen
        - pybind11
        - coin3d
        - pyside2
        - smesh
        - doxygen  # [build_platform == target_platform]
        - hdf5
        - freetype
        - libspnav # [linux]
        - pcl
        - six
        - ply
        - matplotlib-base
        - yaml-cpp
        - pivy
        - noqt6
    run:
        - pyside2
        - vtk
        - {{ pin_compatible('occt', max_pin='x.x.x') }}
        - xerces-c
        - zlib
        - hdf5
        - python
        - coin3d
        - pivy
        - {{ pin_compatible('smesh', max_pin='x.x.x') }}
        - freetype
        - numpy
        - six
        - pyyaml
        - libspnav  # [linux]
        - pcl
        - ply
        - gmsh
        - graphviz
        - requests

about:
    home: https://www.freecad.org/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        FreeCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an
        Open Inventor-compliant 3D scene representation model provided by the
        Coin 3D library, and a broad Python API. The interface is built with Qt.
        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux
        platforms.
    doc_url: https://wiki.freecad.org/Main_Page
    dev_url: https://github.com/FreeCAD/FreeCAD

extra:
    recipe-maintainers:
        - looooo
        - adrianinsaval