build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux: azure
  linux_aarch64: azure
  osx: azure
  win: azure
conda_build:
  pkg_format: '2'
test: native_and_emulated
