travis:
  secure:
    BINSTAR_TOKEN: dgiBsbOGFoL/0YZhH6P2L/1A37TOW0LZzIiSATjX18nFFnJG0XqVazsZcxcxDUe9HeFXGQSHBXuErYDBPo1WMFMYrGR/kFSaARnQBOZ2FLza6B6FB2ijFUvYRP8N6vre8yEevaSLu7zpeE2gwtkQQY1qlYfabgx1DIqRrNmC3C/LW4WrLD+CoEuUTCpcwmIPQ4YUHngcI0yb2JxDYSAoyiy/g3DQpvDlaTc7OkiwbIFUQdA1RL52LBlC10KoYhzY0npRJZnwXjLC6nElwWAxfnJJv1MQf2A1DRQqbvVQUOnYAvzkfPjEFXNt9Zv4DEZjZ/k2fnZEyQYP+8X4PYUs4GtQoukbgHsmiKPreKgPRDwpE3bic5VaOS5ATMAXeg5VMQw6vzbleLLRG/kXOM/5BdIxmww0nkPLYxBkgxk59NiAZk2/FL4rTGjFghbl7VFaLIiNsMV75dRTqeM3muBc0ZMNcA0CV/nAY9pTAq25kYMInuwxGX6wByblILLxKsM9LamBmT5Tk8tgr9l0XA0/vwTHqd5N9WbeLBB97oJH90zBBGm+wxkzNKI/gtl7fNtISgMtruU24j7/ZSLd82GPMoPoAoDXuUWwLLefD0B+pf4BoR5tfWsA660YsZ5rMoc5MEOwSoMwVQnUoVNI2pDa5LKOrtFABy2O/L/wxUHZ5vk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4

provider:
    osx: circle
